use functions in scripts

diff --git a/sdcard/mijia-720p-hack/scripts/S99dropbear b/sdcard/mijia-720p-hack/scripts/S99dropbear
--- a/sdcard/mijia-720p-hack/scripts/S99dropbear
+++ b/sdcard/mijia-720p-hack/scripts/S99dropbear
@@ -4,35 +4,33 @@
 ## author: Jan Sperling , 2017
 
 sd_mountdir="/tmp/sd"
+if [ -r "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh" ]; then
+  . "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh"
+else
+  echo "Unable to load basic functions"
+  exit 1
+fi
+
 NAME="dropbear"
 DESC="SSH server"
 DAEMON="${sd_mountdir}/mijia-720p-hack/bin/${NAME}"
 DAEMON_OPTS="-R -p 22"
 PIDFILE="/var/run/${NAME}.pid"
+LOGFILE="${LOGDIR}/${NAME}.log"
 
-if [ ! -x "${DAEMON}" ]; then
-  echo "Could not find ${DESC} binary"
-  exit 1
-fi
+check_daemon_bin "${DAEMON}" "${DESC}"
 
 case "$1" in
   start)
-    echo "Starting ${DESC}"
-    if [ ! -d /var/run ]; then
-      mkdir -p /var/run
-    fi
     if [ ! -d /etc/dropbear ]; then
       mkdir -p /etc/dropbear
     fi
-
     ## Security Purpose: recover previoys RSA keys from SDCARD
     if [ -s "${sd_mountdir}/mijia-720p-hack/etc/dropbear_ecdsa_host_key" ]; then 
       cp "${sd_mountdir}/mijia-720p-hack/etc/dropbear_ecdsa_host_key" /etc/dropbear
     fi
 
-    start-stop-daemon --start --quiet \
-      --pidfile "${PIDFILE}" --exec "${DAEMON}" -- ${DAEMON_OPTS}
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    start_daemon
 
     ## Security Purpose: Save the keys in the SDCARD
     if [ ! -s "${sd_mountdir}/mijia-720p-hack/etc/dropbear_ecdsa_host_key" ] &&
@@ -41,17 +39,17 @@ case "$1" in
     fi
     ;;
   stop)
-    echo "Stopping ${DESC}"
-    start-stop-daemon --stop --quiet --oknodo \
-      --pidfile "${PIDFILE}"
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    stop_daemon
     ;;
   restart|reload)
     "$0" stop
     "$0" start
     ;;
+  status)
+    status_daemon
+    ;;
   *)
-    echo "Usage: $0 {start|stop|restart}"
+    echo "Usage: $0 {start|stop|restart|status}"
     exit 1
     ;;
 esac
diff --git a/sdcard/mijia-720p-hack/scripts/S99ftpd b/sdcard/mijia-720p-hack/scripts/S99ftpd
--- a/sdcard/mijia-720p-hack/scripts/S99ftpd
+++ b/sdcard/mijia-720p-hack/scripts/S99ftpd
@@ -4,30 +4,38 @@
 ## author: Jan Sperling , 2017
 
 sd_mountdir="/tmp/sd"
-LOGDIR="${sd_mountdir}/log"
-LOGFILE="${LOGDIR}/ftpd.log"
+if [ -r "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh" ]; then
+  . "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh"
+else
+  echo "Unable to load basic functions"
+  exit 1
+fi
+
 NAME="ftpd"
 DESC="FTP server"
-DAEMON="tcpsvd"
+DAEMON="/usr/bin/tcpsvd"
+DAEMON_OPTS="-vE 0.0.0.0 21 ftpd /"
+PIDFILE="/var/run/${NAME}.pid"
+LOGFILE="${LOGDIR}/${NAME}.log"
+
+check_daemon_bin "${DAEMON}" "${DESC}"
 
 case "$1" in
   start)
-    echo "Starting ${DESC}"
-
-    tcpsvd -vE 0.0.0.0 21 ftpd / >> "${LOGFILE}" 2>&1 &
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    start_daemon_background
     ;;
   stop)
-    echo "Stopping ${DESC}"
-    pkill -f '^tcpsvd -vE 0.0.0.0 21 ftpd '
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    stop_daemon_background
     ;;
   restart|reload)
     "$0" stop
     "$0" start
     ;;
+  status)
+    status_daemon
+    ;;
   *)
-    echo "Usage: $0 {start|stop|restart}"
+    echo "Usage: $0 {start|stop|restart|status}"
     exit 1
     ;;
 esac
diff --git a/sdcard/mijia-720p-hack/scripts/S99samba b/sdcard/mijia-720p-hack/scripts/S99samba
--- a/sdcard/mijia-720p-hack/scripts/S99samba
+++ b/sdcard/mijia-720p-hack/scripts/S99samba
@@ -4,44 +4,45 @@
 ## author: Jan Sperling , 2017
 
 sd_mountdir="/tmp/sd"
+if [ -r "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh" ]; then
+  . "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh"
+else
+  echo "Unable to load basic functions"
+  exit 1
+fi
+
 NAME="samba"
 DESC="CIFS server"
 DAEMON="${sd_mountdir}/mijia-720p-hack/bin/smbd"
 DAEMON_OPTS="-D"
 PIDFILE="/var/run/${NAME}.pid"
+LOGFILE="${LOGDIR}/samba/log.smbd"
 
-if [ ! -x "${DAEMON}" ]; then
-  echo "Could not find ${DESC} binary"
-  exit 1
-fi
+check_daemon_bin "${DAEMON}" "${DESC}"
 
 case "$1" in
   start)
-    echo "Starting ${DESC}"
-    if [ ! -d /var/run ]; then
-      mkdir -p /var/run
-    fi
-
     if [ ! -d "${sd_mountdir}/mijia-720p-hack/tmp/samba" ]; then
       mkdir -p "${sd_mountdir}/mijia-720p-hack/tmp/samba"
     fi
+    if [ ! -d "${LOGDIR}/samba" ]; then
+      mkdir -p "${LOGDIR}/samba"
+    fi
 
-    start-stop-daemon --start --quiet --oknodo \
-      --exec "${DAEMON}" -- ${DAEMON_OPTS}
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    start_daemon
     ;;
   stop)
-    echo "Stopping ${DESC}"
-    start-stop-daemon --stop --quiet --oknodo \
-      --pidfile "${PIDFILE}"
-    [ $? = 0 ] && echo "OK" || echo "FAIL"
+    stop_daemon
     ;;
   restart|reload)
     "$0" stop
     "$0" start
     ;;
+  status)
+    status_daemon
+    ;;
   *)
-    echo "Usage: $0 {start|stop|restart}"
+    echo "Usage: $0 {start|stop|restart|status}"
     exit 1
     ;;
 esac
diff --git a/sdcard/mijia-720p-hack/scripts/configure_wifi b/sdcard/mijia-720p-hack/scripts/configure_wifi
--- a/sdcard/mijia-720p-hack/scripts/configure_wifi
+++ b/sdcard/mijia-720p-hack/scripts/configure_wifi
@@ -4,7 +4,12 @@
 ## author: Jan Sperling , 2017
 
 sd_mountdir="/tmp/sd"
-. "${sd_mountdir}/mijia-720p-hack.cfg"
+if [ -r "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh" ]; then
+  . "${sd_mountdir}/mijia-720p-hack/scripts/functions.sh"
+else
+  echo "Unable to load basic functions"
+  exit 1
+fi
 
 if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
   cat << EOF
@@ -17,8 +22,8 @@ EOF
 fi
 
 if [ "$#" -ne 0 ]; then
-  WIFI_SSID="$1"
-  WIFI_PASS="$2"
+  WIFI_SSID="${1}"
+  WIFI_PASS="${2}"
 fi
 
 if [ -n "${WIFI_SSID}" ]; then
@@ -31,39 +36,22 @@ if [ -n "${WIFI_SSID}" ]; then
     WIFI_KEY_MGMT="WPA"
   fi
 
-  if [ "$(/usr/sbin/nvram get miio_ssid)" != "${WIFI_SSID}" ]; then
-    /usr/sbin/nvram set miio_ssid="${WIFI_SSID}"
-    nvram_change=1
+  if [ "$(get_nvram miio_ssid)" != "${WIFI_SSID}" ]; then
+    set_nvram miio_ssid "${WIFI_SSID}"
   fi
-  if [ "$(/usr/sbin/nvram get miio_key_mgmt)" != "${WIFI_KEY_MGMT}" ]; then
-    /usr/sbin/nvram set miio_key_mgmt="${WIFI_KEY_MGMT}"
-    nvram_change=1
+  if [ "$(get_nvram miio_key_mgmt)" != "${WIFI_KEY_MGMT}" ]; then
+    set_nvram miio_key_mgmt "${WIFI_KEY_MGMT}"
   fi
-  if [ "(/usr/sbin/nvram get miio_passwd)" != "${WIFI_PASS}" ]; then
-    usr/sbin/nvram set miio_passwd="${WIFI_PASS}"
-    nvram_change=1
+  if [ "$(get_nvram miio_passwd)" != "${WIFI_PASS}" ]; then
+    set_nvram miio_passwd "${WIFI_PASS}"
   fi
-  if [ "${nvram_change}" -eq 1 ]; then
-    /usr/sbin/nvram set wifi_ready=yes
-    /usr/sbin/nvram commit
+  if [ "$(get_nvram wifi_ready)" != "yes" ]; then
+    set_nvram wifi_ready yes
     if pgrep wpa_supplicant > /dev/null; then
       /mnt/data/imi/imi_init/S92wifi restart
     fi
   fi
 fi
 
-if ! grep -q "^WIFI_SSID=\"${WIFI_SSID}\"" "${sd_mountdir}/mijia-720p-hack.cfg"; then
-  if ! grep -q "^WIFI_SSID="; then
-    echo "WIFI_SSID=\"${WIFI_SSID}\"" >> "${sd_mountdir}/mijia-720p-hack.cfg"
-  else
-    sed -i -e "s/\(^WIFI_SSID)\=.*/\1=\"${WIFI_SSID}\"" "${sd_mountdir}/mijia-720p-hack.cfg"
-  fi
-fi
-if ! grep -q "^WIFI_PASS=\"${WIFI_PASS}\"" "${sd_mountdir}/mijia-720p-hack.cfg"; then
-  if ! grep -q "^WIFI_PASS="; then
-    echo "WIFI_PASS=\"${WIFI_PASS}\"" >> "${sd_mountdir}/mijia-720p-hack.cfg"
-  else
-    sed -i -e "s/\(^WIFI_PASS)\=.*/\1=\"${WIFI_PASS}\"" "${sd_mountdir}/mijia-720p-hack.cfg"
-  fi
-fi
-
+set_basecfg WIFI_SSID "${WIFI_SSID}"
+set_basecfg WIFI_PASS "${WIFI_PASS}"
